### PR TITLE
add parallel heiko's project information

### PR DESCRIPTION
**Pull request by GopherJ**
Data:

```
{
  "Para ID": "2085",
  "Project Name": "Parallel Heiko",
  "Logo": "../../assets/images/heiko.svg",
  "Description (en)": "A decentralized lending & staking protocol built on top of the Polkadot ecosystem.",
  "Description (zh)": "Parallel Heiko作为Parallel在kusama上的先行网，提供去中心化的借贷，质押功能",
  "Parachain Crowdloans Allocation (en)": "",
  "Parachain Crowdloans Allocation (zh)": "",
  "Auction Reward & Reward Vesting Schedule (en)": "",
  "Auction Reward & Reward Vesting Schedule (zh)": "",
  "Financing Information (en)": "",
  "Financing Information (zh)": "",
  "Website Link": "https://parallel.fi",
  "Twitter Link": "https://twitter.com/ParallelFi",
  "Telegram Link": "https://t.me/parallelfi",
  "Discord Link": "https://discord.com/invite/buKKx4dySW",
  "Medium Link": "https://parallelfinance.medium.com",
  "Github Link": "https://github.com/parallel-finance",
  "Owner account": "CrDdFXV729K1ipSRmuyv4ux5uGzmwjEvihvmL29f4T8AScQ"
}
```

Owner account: 
```
CrDdFXV729K1ipSRmuyv4ux5uGzmwjEvihvmL29f4T8AScQ
```

Signature:
```
TBD
```

@yubo-ruan we will need your signature on the `Data`, you can go to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/signing and paste the above `Data` then push your signature to https://github.com/parallel-finance/parachain-projects-info/tree/feat/parallel-heiko branch

### CODE REVIEW

**Comment by GopherJ** [comment]
@yubo

**Comment by GopherJ** [comment]
@yubo-ruan I think you forgot it

**Comment by yakio** [comment]
> @yubo-ruan I think you forgot it, at the same time @yakio is this signature really necessary, I feel it's less useful than you might expect. You can easilly check if the person is from that team:)
Hi @GopherJ 
The signature is important, it means that the information is authorized by the owner, not just a team member.
If your owner account cannot sign data because of multi-signature or proxy account type, please contact us.

**Comment by yakio** [comment]
> @yubo-ruan I think you forgot it, at the same time @yakio is this signature really necessary, I feel it's less useful than you might expect. You can easilly check if the person is from that team:)


Hi @GopherJ
The signature is important, it means that the information is authorized by the owner, not just a team member.
If your owner account cannot sign data because of multi-signature or proxy account type, please contact us.

**Review by carlhong — CHANGES_REQUESTED** [review]
missing signature

**Comment by MittWillson** [comment]
This PR is out of date, please resubmit a new PR if you still need it

**Pull request closed without merging**
