### PR TITLE
Add Bajun for the crowdloan page of Kusama

### PR DESCRIPTION
**Pull request by darkfriend77**
# Checklist

- [x] Use the owner account that submitted registrar_reserve to [sign](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/signing) the project information, and fill in the signature.
- [x] After each update of the project information, please sign the latest data and submit the signature.
- [x] Add a description for your pr, the description includes the original data of the signature, signature account, and signature.

signed description 
`Bajun Network the Kusama parachain of Ajuna Network is a decentralized gaming platform that delivers real value to gamers, without compromising on gameplay.`

owner account
`E3BajuRoG9Wv7RQW6s5vtqMZkLk2khDPjgzVXRwXdd913Uw`

Signature
`0xa807441ed1b5d7982d260533c13fdeb270b2e57bfb24f3214f594767ab198a51fca379065dda96117614415532f7d11da1be40209e7a3cb6fd9a9a520bc88d89`

image

### CODE REVIEW

**Comment by vzxh** [comment]
截屏2022-06-06 下午6 13 35

Hello, the signature fails at verifying, please check~

**Comment by MittWillson** [comment]
Please provide a signature of contents of `networks/kusama/parachain/bajun.json`

**Comment by MittWillson** [comment]
Since there has been no update for a long time, will close it, and submit it if necessary

**Comment by darkfriend77** [comment]
Sry @MittWillson because the provided Signature is not the one in the picture :-(

which should have been this, my fault and apologize for missing this PR.
`0x60716d5df33ce535c15e74c4391ecc938e0ce080c1a487ce6bae4305fb6a760c027cd545d2409242577bdedabb2472d41c87fa5658f9996372a4a740e023f683`

**Pull request closed without merging**
